global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'keycloak'
    # Scrape metrics from all four Keycloak management endpoints
    static_configs:
      - targets:
        - 'sso-1-a.mydomain.com:9000'
        - 'sso-2-a.mydomain.com:9000'
        - 'sso-1-b.mydoman.com:9000'
        - 'sso-2-b.mydomain.com:9000'

    scheme: https
    tls_config:
    # --- THIS PART IS CRITICAL ---
    # It tells Prometheus to use HTTPS and to skip verifying the
    # self-signed/internal certificates on your Keycloak management ports.
    #  insecure_skip_verify: true
    # --- THIS IS THE CORRECTED CONFIG ---
      # We are NOT using 'insecure_skip_verify: true'.
      # Instead, we are telling Prometheus to trust our internal CA.
      ca_file: /etc/prometheus/certs/lab-root-ca.crt